- server/main.lua
Fixed issue with old check and return returning {} regardless of ownership and breaking other checks as you can see now it returns false if not found
The effect of this bug was allowing you to store any vehicle regardless of ownership, you would not be able to retrieve the vehicle but still removes the vehicle
[ x ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
[ x ] My code fits the style guidelines.
[ x ] My PR fits the contribution guidelines.
> Fixed broken database handling

- client/main.lua
- server/main.lua
SpawnVehicle now supports sending props in the spawn call. This PR moves the props setting to the server and off the client to prevent issues with client ownership of a vehicle entity which typically required placing the player in the vehicle to set the props.
> refactor: move vehicle props to serverside spawn

- client/main.lua
- config/client.lua
- config/shared.lua
- server/main.lua
Added a takeOut group of config options to allow further customization by the player.
- warpInVehicle: While false, player no longer warps you into their vehicle upon taking it out. (Default is false)
- doorsLocked: While true, the vehicle doors will no longer be unlocked upon taking the vehicle out, forcing the player to unlock it with their keys. (Default is true)
- engineOff: While true, he vehicles engine will no longer be on automatically, forcing the player to get in and wait for their character to start it before driving off. (Default is true)
Minor UI and style edits
> feat: takeOut config options

- .vscode/settings.json
- client/main.lua
- config/shared.lua
- fxmanifest.lua
- server/main.lua
- Updated to the lib module
- Removed the already broken house garage code
- Fixed the lua annotations in the config
> refactor: utils to lib and remove house garages

- client/main.lua
- config/client.lua
- server/main.lua
- Removed config option visuallyDamageCars as vehicle properties will always be applied
- removed duplicate code that would apply the same vehicle properties as lib.setVehicleProperties does.
- temporarily implemented the server side qb-vehicletuning:server:SaveVehicleProps event. In a future PR, will replace this with a callback, rename it, and likely combine it with other db saves.
> fix: save vehicle props on vehicle storage

- client/main.lua
- server/main.lua
- merged some functions instead of multiple events/callback occurring when a vehicle is parked
- moved the actual entity deletion to the server side
- restructured and renamed checkPlayers to kickOutPeds, although I wonder if this is even needed.
- adding server side state bag to vehicles to store the vehicle id. This is the unique database column identifying owned vehicles. Switching the ownedVehicles checker to use this as the id instead of plate. Future PRs will shift away from using plate as an identifier for a vehicle, since a plate could change. We should be using vehicle id as the primary id of vehicles.
> refactor: outside vehicles tracking vehicle id

- client/main.lua
- server/main.lua
- renamed checkOwnership to isParkable
- use vehicleId instead of plate to lookup vehicles
- minimize query size
- avoid player query, instead opting to use the player object from core to get the player's gang.
> refactor: use vehicleId instead of plate when checking ownership

- client/main.lua
- server/main.lua
This was previously being invoked from the client after the vehicle was spawned. This PR simplifies this to contain less network hops.
> refactor: update vehicle stats when spawning vehicle

- fxmanifest.lua
fix for "Warning: could not find server_script `server/spawn-vehicles.lua` (defined in fxmanifest.lua:22)"
> fix(fxmanifest): use correct file path

- config/server.lua
- server/main.lua
- server/spawn-vehicle.lua
- server/storage.lua
This is an intermittent step. As part of this PR, I also identified some places that we could avoid SQL calls. For example, now that we have vehicleid state bag, we can check it to see if the vehicle is player owned rather than do a db call. Also moved some things around to make a little more sense, like checking if a player has a right to spawn a vehicle before it's spawned instead of after.
Follow-up PRs will start moving some of these storage layer calls to qbx_vehicles. It's useful to see what exactly qbx_garages needs from the database in one place to influence the qbx_vehicles API.
> refactor: move SQL calls to storage layer

- server/spawn-vehicle.lua
While technically correct `not not result` is a bit less readable compared to `result ~= nil`. Additionally adds LIMIT 1 to the SQL query to prevent edge cases where someone makes vehicleId not unique.
> refactor(server/spawn-vehicle): style and limit

- server/spawn-vehicle.lua
It would give nil value error since modelName is not housed there and would error every time a car is taken out of a garage or depot. Does fix the issue.
> fix: getting modelName

- client/main.lua
- server/main.lua
- server/spawn-vehicle.lua
- server/storage.lua
- shared/types.lua
Replace direct database calls with qbx_vehiclekeys exports. 
Blocked by https://github.com/Qbox-project/qbx_vehicles/pull/9
> refactor: use qbx_vehicles

- server/main.lua
- server/spawn-vehicle.lua
- Use qbx_vehicles API for checking ownership of vehicle before spawning instead of direct SQL queries
- Combine checking ownership and getting vehicle, since it is the same query repeated twice
- Extract common code into a shared function for getting the vehicle filtering between retrieving the list of vehicles in a garage that the player has access to, and validating the player has access before spawning. This should fix #48 and may also fix other issues as well as the spawn validation code seemingly had some incorrect state filtering.
> fix: player seeing a vehicle in garage, but not being able to take it out due to ownership error

- client/main.lua
- config/shared.lua
- server/spawn-vehicle.lua
Adds support to access a garage from more than one access point. This can be useful to create a shared pool of vehicles, accessed from multiple locations, such as a network of public garages. Or a bunch of parking spaces in the same vicinity which access the same garage for example.
> feat: support for multiple access points per garage

- client/main.lua
- config/shared.lua
- server/main.lua
- shared/utils.lua
- Using the ox_target filtering code for filtering which groups have access to a garage. This makes the filtering more powerful as multiple groups could be selected, or even specific grades.
- Decouple the group checking from the garage type. This is part of a broader refactor in future PRs to remove most garage types in favor of explicit permissions/filtering. Rather than a garage of type job, it will be a generic garage with a groups filtering applied.
> feat: use ox_target groups filtering

- server/main.lua
Fixes bug where when shared is false the garage would be shared and when shared was true it would not be.
> fix: shared field having the opposite effect

- client/main.lua
Previously, group permissions were checked to create the garage interactions, but not the blip. This caused an issue for players switching jobs who may enter or leave permission for a given garage. I considered doing loop checking to keep the blips/zones created only for people with the job, but I ended up going with a simpler approach, which is to create the garage interactions for all players, show the blips to all players (this was already the case), and check the group permissions at runtime.
A future improvement may be showing/hiding blips based on permissions, but this is probably not a key feature.
> fix: group permissions checked at runtime instead of initial load

- server/main.lua
My pull request changes the config used for getting garages from the shared config to the server config. The server config contains the actual garage data, which fixes the issue of garages not being retrieved correctly and resulting in a nil value / no Garages.
> fix(server): get the garages from the correct config

- client/main.lua
- config/client.lua
- server/main.lua
qbx_garage server side is a pretty generic garage backend with an export API. This introduces a config option to disable to built-in client files so that someone can make a custom UI that hooks into the qbx_garages backend.
> feat: disable client config option for custom UIs

- server/spawn-vehicle.lua
GetEntityCoords returns a Vec3 value not a Vec4 which are not directly compatible. Adding .xyz creates a temporary vec3 for the vector distance calculation
> fix(spawn-vehicle): use vec3 not vec4 for dist check

- server/main.lua
NPWD garage app needs to get a list of current garages. It's current implementation does not account for dynamically registered garages. This export allows the garages to be retrieved at run time. Additionally an event is triggered when a new garage is registered allowing for other resources to listen and call the export as needed.
> feat(server/main): GetGarages export

- client/main.lua
- config/server.lua
the canAccess function was attempting to run on the client, but as functions can't be passed across the network, this would cause an error. Instead, the client calls have been removed and the config language no longer states it can be run on the client.
> fix: canAccess function runs only on server

- config/server.lua
Addresses a typo in the configuration table for garage groups. Previously, the garage groups configuration was set incorrectly, causing garage.groups to be received as nil
Changes Made: Corrected the typo in the Config from group to groups.
This fix ensures that garage.groups is now correctly recognized and populated, preventing it from being received as nil.
> Fixed job and gang garages

- server/spawn-vehicle.lua
Useful for resources that want to apply additional properties on vehicles after they've been spawned in.
> feat(server): server event when a vehicle is spawned

- client/main.lua
Registers zones and blips on client start instead of resource start / login.
The reason is if a user changes characters garage zones and blips will be duped as they are never removed.
This is better then just removing zones / blips on logout as all the checks are done after entering a zone and pressing `E` or whatever key it is
Closes #136
> fix(client): Register blips on client start
