client/main.lua
Made changes to the code to save and load vehicle status values. During loading the correct damage will be loaded to the cars not randomized values
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? yes
- Does your code fit the style guidelines? yes
- Does your PR fit the contribution guidelines? hope so
=> Proper vehicle damage instead of randomized values

client/main.lua, fxmanifest.lua
qb-menu to ox.lib conversion
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? - **Yes**
- Does your code fit the style guidelines? - **Yes**
- Does your PR fit the contribution guidelines? - **Yes**
=> feat(client/main): qb-menu to ox.lib

client/main.lua
Fixes a small typo
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [no] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]
=> fix(client/main): typo

client/main.lua
<br> is not used to newline in ox_lib textui
If your PR is to fix an issue mention that issue here
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? Yes
- Does your code fit the style guidelines? Yes
- Does your PR fit the contribution guidelines? Yes
=> <br> not supported in ox_lib

client/main.lua
This will fix an error that appears when you pull a vehicle from the garage, the damage check is checking a status that doesn't exist in the libs.
If your PR is to fix an issue mention that issue here
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? **YES**
- Does your code fit the style guidelines? **YES**
- Does your PR fit the contribution guidelines? **YES**
=> Fix an error with vehicle damage

.github/workflows/lint.yml, client/main.lua, fxmanifest.lua
Switched out the old polyzone for ox_lib zones
If your PR is to fix an issue mention that issue here
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
- Yes
- Does your code fit the style guidelines? [yes/no]
- Yes
- Does your PR fit the contribution guidelines? [yes/no]
- Yes
=> Switched out the old polyzone for ox_lib zones

server/main.lua
- QBCore.Functions.CreateVehicle already returns the netId
credit.. berkieb
=> fix(server): send right id to client

client/main.lua, server/main.lua
Fixes vehicle spawning, to clarify, the wait before setting the vehicle properties is to make sure the game has registered the vehicle before applying those props. I had an issue with that and that fixed it.
=> Fix vehicle spawning

client/main.lua
- Fix storing vehicle in garage
- Fix notification incorrectly swapped
=> fix(client/main): can't store vehicle in garage

client/main.lua
Changed number 0 to 1 so that the car gets stored in the garage
It fixes the issue where you try to store the vehicle in any garage and it doesn't get stored 
- [x ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x ] My code fits the style guidelines.
- [x ] My PR fits the contribution guidelines.
=> Fix cars not saving

locales/cs.lua
=> Add cs.lua translate

client/main.lua, fxmanifest.lua, server/main.lua
Small refactor for recent core updates. Untested.
=> refactor: Refactor for core updates

client/main.lua, server/main.lua
Finish the core exports for the server side notifications and swap the drawtext/hidetext exports for ox_lib
=> fix: finish core exports and showTextUI

server/main.lua
- Fix an issue with the impound
=> fix: impound

client/main.lua, config/server.lua, locales/en.lua, server/main.lua
- Refactor the vehicle list/selection process
- camelCase local functions
- Defaults vehicles to impound upon restart
=> refactor: vehicle list and style fix

client/main.lua, config/server.lua, server/main.lua
- Adds proper impound fees instead of only being used for confiscated vehicles
- Refactoring of the GetGarageVehicles callback
- Impound enabler and percentage options added to server configuration
=> feat: proper impound fee

client/main.lua, config/shared.lua
- Adjust all garage and impound coordinates from vec3 to vec4
- Change lib.zones.box and addBoxZones to use the vec4 w axis instead of 0
- Rename the duplicate garage caears24 to littleseoul
- Add Lua Annotations to the config
=> fix: adjust garage coordinates

client/main.lua
Switch progressColor and classes to proper enumerations and place the StateLabels set outside of the getStateLabel function
=> refactor(client): enumerations

client/main.lua
- Begin properly organizing the functions and applying the appropriate lua annotations
- Reformat all strings into `(''):format()`
- Should fix #35 
- Removes players being sent to nearest garage coords when kicked out of vehicle being placed into garage
=> fix(client): organization and formatting

server/main.lua
Untested but should work fine.
=> fix(server): utilize warping config option.

.vscode/settings.json
=> chore: MySQL to lint

server/main.lua
Test case:
- initial conditions: 2 vehicles impound, 1 public garage (out)
- get one impound vehicle
- check impound list (vehicle disappear list)
- buy new vehicle
- check impound list (no new vehicles)
- get second vehicle from impound 
- check list (one vehicle from public garage)
- delete vehicles with txadmin (3 vehicles impound)
- get one impound vehicle to a public parking lot
- check parking list (vehicle shown)
- move the vehicle to another parking lot (where the impounded vehicle is registered)
- two vehicles visible (impounded cannot be taken)
- check another garage
- check impound
- take vehicle
- try take again (can't)
- get registered and impounded vehicle from impound
- park elsewhere
- check garage
- check old garage
- check impound
conclusion: results as intended
I didn't …
=> fix: outside vehicles checking

server/main.lua, shared/types.lua
- Use enum instead of string literals
- get rid of string concatenation to construct SQL queries
=> refactor: add GarageType.HOUSE

client/main.lua, server/main.lua, server/spawn-vehicle.lua
trust the clients less by having clients supply only the vehicleId and garageName, the server fetches the rest of the data from config/storage
=> refactor: send smaller payloads over the network

client/main.lua, server/main.lua
reducing network payload size and changing a net event handler to a local clientside function
=> refactor: switch payDepotPrice to a callback

client/main.lua, config/shared.lua, server/main.lua, server/spawn-vehicle.lua
- also sneaking in a few config field renames
Pass less through to server events/callbacks in cases where the server can derive the same data
=> refactor: simplify args

client/main.lua
The depot takeout function wasn't being supplied with the accessPoint. This fixes that
=> fix(client): missing accessPoint to takeOutDepot

config/shared.lua
=> fix(config): typo preventing warping

server/main.lua, server/storage.lua
Using errors as values for error scenarios the client is expected to handle
=> feat: new exports to transfer garages and change the depot price

client/main.lua, config/client.lua
Ill-suited towards garage zones since target requires an object to raycast to.
=> feat!: remove ox_target support

config/server.lua, server/spawn-vehicle.lua, server/storage.lua
There are many ways to set impound fee, so making it a configuration function to encourage an easy way to customize.
=> feat!: make impound fee a configurable function

fxmanifest.lua
Fixes the importing of the new ox_locales
=> fix(manifest): locale importing

config/server.lua
- Tested to see that naming the blips the same works in seeing them under the same category on the map screen.
=> feat(config/server): consolidate blips for default garages

client/main.lua, config/client.lua, config/server.lua
- add optional drop point to separate the location where vehicles are dropped and where the menu is accessed from
- converted poly box into points. Each garage has one large point that when in range creates the other points for individual locations and draws markers to indicate their position.
Don't know why there are lint errors. Seems like creating a point from within a point is causing the issue somehow.
=> feat: add optional drop point and draw markers

server/main.lua
Uses qbx_vehicles to get the vehicleId given the plate as a fallback if the statebag isn't set. This makes the statebag an optional optimization rather than be required to make qbx_garages compatible with other scripts that may not be setting the statebag.
Blocked on qbx_vehicles v1.2.0 release
=> feat: get vehicleId from plate if the statebag is not set

server/main.lua
=> fix(server/main): removed assertion for vehicleId being set

config/server.lua, server/main.lua
Fixes bugs when checking for access server sided
=> Fixes bugs when checking for access server sided

client/main.lua, config/server.lua, locales/en.json, server/spawn-vehicle.lua
=> Fix [Vehicle Spawn #115] + Fix dropPoint to Default to spawn or coords

server/main.lua
=> fix: function name mistake

server/storage.lua
=> fix: query string

server/main.lua
Adds ox_lib version checking for when this gets new releases
=> feat(server/main): version checking

fxmanifest.lua
Removes the duplicate version metadata added by the release action
=> fix(manifest): duplicate release metadata

locales/it.json
=> Added it.json

client/main.lua, server/main.lua, server/spawn-vehicle.lua
Moves the payment from a callback triggered before spawn. To inside the spawn code after it validates the vehicle can spawn
Closes #137
=> fix(client/server): Validate before payment
